[tool.isort]
  combine_as_imports     = true
  default_section        = "THIRDPARTY"
  force_grid_wrap        = 0
  include_trailing_comma = true         # Ensures compatibility with Black
  known_first_party      = [  ]
  line_length            = 120          # Matches Black's default line length
  multi_line_output      = 0            # Preferred multi-line format
  profile                = "black"      # Ensures isort follows Black's formatting style
  skip_gitignore         = true

[tool.black]
  include                   = '\.pyi?$' # Formats only Python files
  line_length               = 120       # Consistent with isort
  skip-string-normalization = false     # Set to true if you don’t want Black to change string quotes
  target-version            = [  ]      # Adjust as per your Python versions
